### ISSUE TITLE
8/25 이슈 목록

### ISSUE THREAD

**Issue by codemilli** [fedgkr/feconf2020#18]
### todo
* [x] 신청 완료 후 이메일 보내기
* [x] 신청 테스트
* [x] 스폰서 리스트 모션 버그 픽스
* [x] 모바일 모달 스크롤링
* [x] Line 모션 UI와 싱크 맞추기 #17 
  * 문구 변경 후 진행하기로
